let assert,callFunction;_273‍.w("assert",[["strict",["assert"],function(v){assert=v}]]);_273‍.w("./call_function.js",[["callFunction",["callFunction"],function(v){callFunction=v}]]);/* npm t exercises/exception-handling/call_function_test.js
Instructions:
– Change call_function.js so that it passes the test.
*/





test('monthToNumber', () => {
  assert.deepEqual(
    callFunction(() => { return 'abc' }),
    { success: 'abc' });
  
  const err = new Error('Failed!');
  assert.deepEqual(
    callFunction(() => { throw err }),
    { failure: err });
});
